package:
  name: kaldi-io-core
  version: "0.1"

source:
  git_url: https://github.com/kaldi-asr/kaldi.git
  git_rev: 3d16b2366c261f329a1820ee6efa9176e8f00aa7
  patches:
    - kaldi_io.patch

requirements:
  build:
    # - gcc 4.8.5 [linux]
    # - libgcc >=4.8.4 [linux]
    - python
    - openblas [linux]
  run:
    - libgcc >=4.8.4 [linux]
    - openblas [linux]

build:
  detect_binary_files_with_prefix: True

test:
  requires:
    # - gcc 4.8.5 [linux]
    - pkg-config [osx]

about:
  license_file: COPYING
  summary: "Kaldi compilation of base, util, matrix, and thread with openBLAS"