package:
  name: pydrobert-kaldi
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../..

requirements:
  build:
    - gcc >=4.8.5 [linux]
    - python
    - numpy
    - swig >=3.0
    - kaldi-io-core
    - pkgconfig
    - pkg-config [osx]
  run:
    - gcc >=4.8.5 [linux]
    - python
    - numpy
    - future
    - six
    - enum34 [py2k]
    - kaldi-io-core

build:
  detect_binary_files_with_prefix: True

test:
  source_files:
    - tests
  requires:
    - nose
  imports:
    - pydrobert
    - pydrobert.kaldi
    - pydrobert.kaldi._internal
    - pydrobert.kaldi.tables

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  license: Apache
  license_file: LICENSE
  summary: "wrapped SWIG bindings for Kaldi"
