{% if environ.get('TRAVIS', False) %}
  {% set version = environ.get('TRAVIS_BRANCH', '0.0').replace('v', '') %}
  {% set build_num = environ['TRAVIS_BUILD_NUMBER'] %}
{% elif environ.get('APPVEYOR', False) %}
  {% set version = environ.get('APPVEYOR_REPO_TAG_NAME', '0.0').replace('v', '') %}
  {% set build_num = environ['APPVEYOR_BUILD_NUMBER'] %}
{% else %}
  {% set version = environ.get('GIT_DESCRIBE_TAG', '0.0').replace('v','') %}
  {% set build_num = environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% endif %}
# blas_impl one of openblas, mkl, or accelerate

package:
  name: pydrobert-kaldi
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python {{ python }}
    - vc {{ vc }}                          [win]
    - numpy 1.11.3
    - setuptools
    - setuptools_scm
    - swig >=3.0.8
{% if blas_impl == 'mkl' %}
    - mkl-devel
{% else %}
    - nomkl
{%if blas_impl == 'openblas' %}
    - openblas-devel
{% endif %}
{% endif %}
  build:
    - {{ compiler('cxx') }}
  run:
    - python {{ python }}
    - vc {{ vc }}                          [win]
{% if blas_impl == 'mkl' %}
    - mkl
{% else %}
    - nomkl
{%if blas_impl == 'openblas' %}
    - libopenblas
{% endif %}
{% endif %}
{% if blas_impl != 'mkl' %}
    - nomkl                                [not win]
{% endif %}
    # there have been no major changes in the api since 1.11.3 (currently at
    # 1.13). We'll see how long this lasts us
    - {{ pin_compatible('numpy') }}
    - future
    - six
    - enum34                               [py2k]

build:
  number: {{ build_num }}
  detect_binary_files_with_prefix: False
  features:
{% if blas_impl != 'mkl' %}
    - nomkl                                [not win]
{% endif %}
    - {{ vc_feat }}                        [win]

test:
  source_files:
    - tests
  requires:
    - pytest
    - scipy
  imports:
    - pydrobert
    - pydrobert.kaldi
  commands:
    - pytest

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  license: Apache 2.0
  license_file: LICENSE
  summary: Kaldi Swig bindings for Python
  summary: Kaldi Swig bindings for Python
