# This covers the remainder of py3 builds in travis when deploying
python:
  - 3.4
  - 3.5
  - 3.6
blas_impl:
  - mkl
  - openblas   [linux]
  - accelerate [osx]
matrix:
  exclude:
    - python: 3.6
      blas_impl: mkl
