version: build.{build}.branch.{branch}

environment:
  matrix:
    - image: Visual Studio 2015
      PY_VER: 3.6
      MINICONDA_PATH: "C:\\Miniconda3-x64"
    - image: Visual Studio 2015
      PY_VER: 3.5
      MINICONDA_PATH: "C:\\Miniconda3-x64"
    # 3.4 ought to work, and 2.7 ought not to work, but not because it's missing
    # the visual studio compiler. I'll attribute this to growing pains of
    # Conda Build 3. Either way, I'm commenting them out
    # - image: Visual Studio 2010
    #   PY_VER: 3.4
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2008
    #   PY_VER: 2.7
    #   MINICONDA_PATH: "C:\\Miniconda-x64"

clone_depth: 1

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
  - cmd: call %MINICONDA_PATH%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q --all
  - cmd: conda install conda-build anaconda-client

install:
  - cmd: conda build recipe --no-test --python %PY_VER%
  - cmd: conda create -n test python=%PY_VER% pytest
  - cmd: activate test
  - cmd: conda install pydrobert-kaldi --use-local

build: false

test_script:
  - pytest

deploy_script:
    - ps: >-
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
          $env:ANACONDA_PATH = (Join-Path $env:MINICONDA_PATH Scripts\anaconda)
          $env:TARS = (Join-Path -Path $env:MINICONDA_PATH -ChildPath 'conda-bld\win-64\pydrobert-kaldi-*.tar.bz2' -Resolve)
          cmd /c "$env:ANACONDA_PATH 2>&1" -t $env:ANACONDA_TOKEN upload -u sdrobert --register $env:TARS
        }
