version: 0.0.0

environment:
  matrix:
    - image: Visual Studio 2015
      PY_VER: 3.6
      MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2015
    #   PY_VER: 3.5
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2010
    #   PY_VER: 3.4
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
  ANACONDA_TOKEN:
    secure: /udeHG5jwcZKZAJbKIfb7obq541yU+xFuDzLtMh6tec=

init:
  - cmd: call %MINICONDA_PATH%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q --all
  - cmd: conda install conda-build anaconda-client

install:
  - cmd: for /f "delims=" %%i in ('git describe --tags --abbrev=0') do set VERSION=%%i
  - cmd: appveyor UpdateBuild -Version %VERSION%
  - cmd: conda build recipe --no-test --python %PY_VER%
  - cmd: conda create -n test python=%PY_VER% pytest
  - cmd: activate test
  - cmd: conda install pydrobert-kaldi --use-local

build: false

test_script:
  - cmd: pytest

# deploy_script:
#   - cmd: anaconda -t %ANACONDA_TOKEN% upload %MINICONDA_PATH%\conda-bld\win-64\pydrobert-kaldi-*.tar.bz2
