version: 0.0.{build}

environment:
  matrix:
    - image: Visual Studio 2015
      PY_VER: 3.6
      MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2015
    #   PY_VER: 3.5
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2010
    #   PY_VER: 3.4
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"

init:
  - cmd: call %MINICONDA_PATH%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q --all
  - cmd: conda install conda-build anaconda-client

install:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH)-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
      }
  - cmd: conda build recipe --no-test --python %PY_VER%
  - cmd: conda create -n test python=%PY_VER% pytest
  - cmd: activate test
  - cmd: conda install pydrobert-kaldi --use-local

build: false

test_script:
  - pytest

deploy_script:
  - ps: >-
      if ($env:APPVEYOR_REPO_BRANCH -eq "master")
      {
        $env:LABEL = main
      }
      else
      {
        $env:LABEL = $env:APPVEYOR_REPO_BRANCH
      }
  - ps: $env:ANACONDA_PATH = (Join-Path $env:MINICONDA_PATH Scripts\anaconda)
  - ps: $env:TARS = (Join-Path -Path $env:MINICONDA_PATH -ChildPath 'conda-bld\win-64\pydrobert-kaldi-*.tar.bz2' -Resolve)
  - ps: cmd /c "$env:ANACONDA_PATH 2>&1" -t $env:ANACONDA_TOKEN upload -u sdrobert --register $env:TARS -l $env:LABEL
