version: 0.0.0

environment:
  matrix:
    - image: Visual Studio 2015
      PY_VER: 3.6
      MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2015
    #   PY_VER: 3.5
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
    # - image: Visual Studio 2010
    #   PY_VER: 3.4
    #   MINICONDA_PATH: "C:\\Miniconda3-x64"
  ANACONDA_TOKEN:
    secure: /udeHG5jwcZKZAJbKIfb7obq541yU+xFuDzLtMh6tec=

init:
  - ps: $env:MINICONDA_PATH\Scripts\activate
  - ps: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q --all
  - cmd: conda install conda-build anaconda-client

install:
  - ps: $env:VERSION = (git describe --tags --abbrev=0)
  - ps: Update-AppveyorBuild -Version "$env:VERSION.$env:$APPVEYOR_BUILD_NUMBER"
  - ps: conda build recipe --no-test --python $env:PY_VER
  - ps: conda create -n test python=$env:PY_VER pytest
  - ps: activate test
  - ps: conda install pydrobert-kaldi --use-local

build: false

test_script:
  - pytest

deploy_script:
  - ps: anaconda -t $env:ANACONDA_TOKEN upload $env:MINICONDA_PATH\conda-bld\win-64\pydrobert-kaldi-*.tar.bz2
