os:
  - osx
  - linux
language: generic # not true
env:
  - PY_VER=2.7
  - PY_VER=3.6
before_install:
  - . recipe/travis_deploy.sh || exit 1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$PY_VER" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$PY_VER" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install conda-build anaconda-client
  - conda create -n test python=${PY_VER} pytest
install:
  - conda build recipe --no-test --python ${PY_VER} -m recipe/ci_build.yaml
  - . activate test || exit 1
  - conda install pydrobert-kaldi --use-local
script:
  - pytest
deploy:
  - provider: script
    script: . deactivate; . recipe/travis_deploy.sh
    skip_cleanup: true
    on:
      tags: true
