language: python
python:
  - 2.7
  - 3.6
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install conda-build anaconda-client
  - conda create -n test python=${TRAVIS_PYTHON_VERSION} pytest
install:
  - conda build recipe --no-test --python ${TRAVIS_PYTHON_VERSION}
  - source activate test
  - conda install pydrobert-kaldi --use-local
script:
  - pytest
deploy:
  - provider: script
    script: source recipe/anaconda_deploy.sh
    on:
      tags: true
    skip_cleanup: true
# install:
#   - sudo apt-get install libopenblas-dev
#   - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#       wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#     else
#       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda config --add channels anaconda
#   - conda update -q --all
#   - conda info -a
#   - conda install conda-build
#   - export CONDA_PY=${TRAVIS_PYTHON_VERSION}
#   - conda build . --no-test
#   - conda create -n test python=${TRAVIS_PYTHON_VERSION} pytest -y
#   - source activate test
#   - conda install pydrobert-kaldi --use-local
# script: 
#   - pytest
