os:
  - osx
  - linux
language: generic # not true
env:
  - PY_VER=2.7
  - PY_VER=3.6
before_install:
  - git fetch --tags
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$PY_VER" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$PY_VER" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install conda-build anaconda-client
  - conda create -n test python=${PY_VER} pytest
install:
  - conda build recipe --no-test --python ${PY_VER}
  - source activate test
  - conda install pydrobert-kaldi --use-local
script:
  - pytest
deploy:
  - provider: script
    script: source deactivate || true; bash recipe/anaconda_deploy.sh main
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: source deactivate || true; bash recipe/anaconda_deploy.sh dev
    skip_cleanup: true
    on:
      branch: dev
# install:
#   - sudo apt-get install libopenblas-dev
#   - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#       wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#     else
#       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda config --add channels anaconda
#   - conda update -q --all
#   - conda info -a
#   - conda install conda-build
#   - export CONDA_PY=${TRAVIS_PYTHON_VERSION}
#   - conda build . --no-test
#   - conda create -n test python=${TRAVIS_PYTHON_VERSION} pytest -y
#   - source activate test
#   - conda install pydrobert-kaldi --use-local
# script: 
#   - pytest
