package:
  name: pydrobert-kaldi
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.0') }}

source:
  path: .

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
    - setuptools_scm
    - openblas
    - swig >=3.0
    - pytest-runner
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('openblas') }}
    - future
    - six
    - enum34 # [py2k]

build:
  detect_binary_files_with_prefix: True

test:
  source_files:
    - tests
  requires:
    - pytest
    - scipy
  imports:
    - pydrobert
    - pydrobert.kaldi

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  license: Apache 2.0
  license_file: LICENSE
