package:
  name: pydrobert-kaldi
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.0') }}

source:
  path: .

requirements:
  host:
    - python
    - numpy
    - setuptools
    - setuptools_scm
    - swig >=3.0.8
    - pytest-runner
    - mkl                                  [not nomkl]
    - mkl-include                          [not nomkl]
    - openblas                             [nomkl and linux]
  build:
    - {{ compiler('cxx') }}
  run:
    # let link libraries be downstream deps
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - future
    - six
    - enum34                               [py2k]

build:
  skip: True                               [win]
  detect_binary_files_with_prefix: False
  features:
    - nomkl                                [nomkl]

test:
  source_files:
    - tests
  requires:
    - pytest
    - scipy
  imports:
    - pydrobert
    - pydrobert.kaldi

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  license: Apache 2.0
  license_file: LICENSE
  summary: Kaldi Swig bindings for Python
